
package com.alcatel_lucent.www.wsp.ns._2008._05._27.ics.phonehandlerService;


import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AlcPhoneHandlerService", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/05/27/ics/phonehandlerService", wsdlLocation = "file:/C:/jaxws-ri/bin/AlcPhoneHandler.wsdl")
public class AlcPhoneHandlerService
    extends Service
{

    private final static URL ALCPHONEHANDLERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.alcatel_lucent.www.wsp.ns._2008._05._27.ics.phonehandlerService.AlcPhoneHandlerService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.alcatel_lucent.www.wsp.ns._2008._05._27.ics.phonehandlerService.AlcPhoneHandlerService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/jaxws-ri/bin/AlcPhoneHandler.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/jaxws-ri/bin/AlcPhoneHandler.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ALCPHONEHANDLERSERVICE_WSDL_LOCATION = url;
    }

    public AlcPhoneHandlerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AlcPhoneHandlerService() {
        super(ALCPHONEHANDLERSERVICE_WSDL_LOCATION, new QName("http://www.alcatel-lucent.com/wsp/ns/2008/05/27/ics/phonehandlerService", "AlcPhoneHandlerService"));
    }

    /**
     * 
     * @return
     *     returns AlcPhoneHandlerPortType
     */
    @WebEndpoint(name = "AlcPhoneHandlerPort")
    public AlcPhoneHandlerPortType getAlcPhoneHandlerPort() {
        return super.getPort(new QName("http://www.alcatel-lucent.com/wsp/ns/2008/05/27/ics/phonehandlerService", "AlcPhoneHandlerPort"), AlcPhoneHandlerPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AlcPhoneHandlerPortType
     */
    @WebEndpoint(name = "AlcPhoneHandlerPort")
    public AlcPhoneHandlerPortType getAlcPhoneHandlerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.alcatel-lucent.com/wsp/ns/2008/05/27/ics/phonehandlerService", "AlcPhoneHandlerPort"), AlcPhoneHandlerPortType.class, features);
    }

}
