/**
 * AlcPhonePortType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneService;

public interface AlcPhonePortType extends java.rmi.Remote {
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetAccountInfoResponse getAccountInfo(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetAccountInfoRequest getAccountInfoRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetCapabilitiesResponse getCapabilities(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetCapabilitiesRequest getCapabilitiesRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetGlobalPhoneStateResponse getGlobalPhoneState(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetGlobalPhoneStateRequest getGlobalPhoneStateRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.NomadLoginResponse nomadLogin(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.NomadLoginRequest nomadLoginRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.PermanentNomadLoginResponse permanentNomadLogin(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.PermanentNomadLoginRequest permanentNomadLoginRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.NomadLogoutResponse nomadLogout(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.NomadLogoutRequest nomadLogoutRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetNomadicStateResponse getNomadicState(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetNomadicStateRequest getNomadicStateRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetNomadicRightResponse getNomadicRight(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetNomadicRightRequest getNomadicRightRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetLineStateResponse getLineState(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetLineStateRequest getLineStateRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.MakeCallResponse makeCall(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.MakeCallRequest makeCallRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.MakePrivateCallResponse makePrivateCall(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.MakePrivateCallRequest makePrivateCallRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.MakeBusinessCallResponse makeBusinessCall(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.MakeBusinessCallRequest makeBusinessCallRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.MakeCorrelatorCallResponse makeCorrelatorCall(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.MakeCorrelatorCallRequest makeCorrelatorCallRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.SendAssociateDataResponse sendAssociateData(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.SendAssociateDataRequest sendAssociateDataRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.TakeCallResponse takeCall(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.TakeCallRequest takeCallRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.HoldCallResponse holdCall(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.HoldCallRequest holdCallRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.ClearCallResponse clearCall(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.ClearCallRequest clearCallRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.ConferenceCallResponse conferenceCall(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.ConferenceCallRequest conferenceCallRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.TransferCallResponse transferCall(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.TransferCallRequest transferCallRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.DeflectCallResponse deflectCall(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.DeflectCallRequest deflectCallRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.DeflectCallToVoiceMailResponse deflectCallToVoiceMail(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.DeflectCallToVoiceMailRequest deflectCallToVoiceMailRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.CancelConferenceCallResponse cancelConferenceCall(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.CancelConferenceCallRequest cancelConferenceCallRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.TransferConferenceCallResponse transferConferenceCall(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.TransferConferenceCallRequest transferConferenceCallRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.ReleaseConferenceCallResponse releaseConferenceCall(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.ReleaseConferenceCallRequest releaseConferenceCallRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.BlindTransferCallResponse blindTransferCall(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.BlindTransferCallRequest blindTransferCallRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.ParkCallResponse parkCall(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.ParkCallRequest parkCallRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.UnParkCallResponse unParkCall(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.UnParkCallRequest unParkCallRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.OverflowToVoiceMailResponse overflowToVoiceMail(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.OverflowToVoiceMailRequest overflowToVoiceMailRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetCallRecordCapabilitiesResponse getCallRecordCapabilities(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetCallRecordCapabilitiesRequest getCallRecordCapabilitiesRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetTelephonyCapabilitiesResponse getTelephonyCapabilities(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetTelephonyCapabilitiesRequest getTelephonyCapabilitiesRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.SendDtmfResponse sendDtmf(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.SendDtmfRequest sendDtmfRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetCallLogCapabilitiesResponse getCallLogCapabilities(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetCallLogCapabilitiesRequest getCallLogCapabilitiesRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetNbUnansweredCallResponse getNbUnansweredCall(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetNbUnansweredCallRequest getNbUnansweredCallRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetCallLogResponse getCallLog(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetCallLogRequest getCallLogRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.ModifyCallLogResponse modifyCallLog(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.ModifyCallLogRequest modifyCallLogRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.DeleteCallLogResponse deleteCallLog(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.DeleteCallLogRequest deleteCallLogRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.DeleteAllCallLogResponse deleteAllCallLog(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.DeleteAllCallLogRequest deleteAllCallLogRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetVoiceMailMessagesNbResponse getVoiceMailMessagesNb(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetVoiceMailMessagesNbRequest getVoiceMailMessagesNbRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetVoiceMailInfoResponse getVoiceMailInfo(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetVoiceMailInfoRequest getVoiceMailInfoRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetVoiceMailPrefixesResponse getVoiceMailPrefixes(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetVoiceMailPrefixesRequest getVoiceMailPrefixesRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetCallBackResponse getCallBack(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetCallBackRequest getCallBackRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.DeleteCallBackResponse deleteCallBack(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.DeleteCallBackRequest deleteCallBackRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.DeleteAllCallBackResponse deleteAllCallBack(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.DeleteAllCallBackRequest deleteAllCallBackRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.InvokeCallBackResponse invokeCallBack(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.InvokeCallBackRequest invokeCallBackRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.InvokeCallBackDuringCallResponse invokeCallBackDuringCall(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.InvokeCallBackDuringCallRequest invokeCallBackDuringCallRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.StartRecordResponse startRecord(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.StartRecordRequest startRecordRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.StopRecordResponse stopRecord(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.StopRecordRequest stopRecordRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.PauseRecordResponse pauseRecord(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.PauseRecordRequest pauseRecordRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.ResumeRecordResponse resumeRecord(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.ResumeRecordRequest resumeRecordRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetRecordStateResponse getRecordState(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetRecordStateRequest getRecordStateRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetCurrentCallInfoResponse getCurrentCallInfo(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetCurrentCallInfoRequest getCurrentCallInfoRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetTelephonicStateResponse getTelephonicState(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetTelephonicStateRequest getTelephonicStateRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetBasicTelephonicStateResponse getBasicTelephonicState(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.GetBasicTelephonicStateRequest getBasicTelephonicStateRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.IsPcmmResponse isPcmm(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.IsPcmmRequest isPcmmRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.SendMessToPcmmResponse sendMessToPcmm(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.SendMessToPcmmRequest sendMessToPcmmRequest) throws java.rmi.RemoteException;
    public com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.IsVoipReadyResponse isVoipReady(com.alcatel_lucent.www.wsp.ns._2008._03._26.ics.phoneSchema.IsVoipReadyRequest isVoipReadyRequest) throws java.rmi.RemoteException;
}
