
package com.alcatel_lucent.test.soapstub.fwmanagement;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.CreateFrameworkUserRequest;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.CreateFrameworkUserResponse;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.CreateVoiceMailBoxRequest;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.CreateVoiceMailBoxResponse;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.DeleteFrameworkUserRequest;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.DeleteFrameworkUserResponse;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.DeleteVoiceMailBoxRequest;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.DeleteVoiceMailBoxResponse;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.GetAvailableDepartmentsRequest;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.GetAvailableDepartmentsResponse;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.GetAvailableDialingRulesRequest;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.GetAvailableDialingRulesResponse;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.GetAvailableDtmfMappingsRequest;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.GetAvailableDtmfMappingsResponse;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.GetAvailableVoiceMailProfilesRequest;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.GetAvailableVoiceMailProfilesResponse;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.GetAvailableVoiceMailSystemsRequest;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.GetAvailableVoiceMailSystemsResponse;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.GetFrameworkUserRequest;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.GetFrameworkUserResponse;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.GetFrameworkUsersRequest;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.GetFrameworkUsersResponse;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.GetOtsAccountRequest;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.GetOtsAccountResponse;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.GetSystemInfoRequest;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.GetSystemInfoResponse;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.GetVoiceMailBoxRequest;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.GetVoiceMailBoxResponse;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.GetVoiceMailBoxesRequest;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.GetVoiceMailBoxesResponse;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.GetVoiceMailProfileRequest;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.GetVoiceMailProfileResponse;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.LoadFrameworkUsersRequest;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.LoadFrameworkUsersResponse;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.LoadVoiceMailBoxesRequest;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.LoadVoiceMailBoxesResponse;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.ObjectFactory;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.UpdateFrameworkUserRequest;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.UpdateFrameworkUserResponse;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.UpdateOtsAccountRequest;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.UpdateOtsAccountResponse;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.UpdateVoiceMailBoxRequest;
import com.alcatel_lucent.test.soapstub.types.fwmanagement.UpdateVoiceMailBoxResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AlcFwManagementPortType", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementDefinitions")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AlcFwManagementPortType {


    /**
     * 
     * @param input
     * @return
     *     returns com.alcatel_lucent.test.soapstub.types.fwmanagement.GetSystemInfoResponse
     */
    @WebMethod(action = "getSystemInfo")
    @WebResult(name = "getSystemInfoResponse", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "output")
    public GetSystemInfoResponse getSystemInfo(
        @WebParam(name = "getSystemInfoRequest", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "input")
        GetSystemInfoRequest input);

    /**
     * 
     * @param input
     * @return
     *     returns com.alcatel_lucent.test.soapstub.types.fwmanagement.GetAvailableDepartmentsResponse
     */
    @WebMethod(action = "getAvailableDepartments")
    @WebResult(name = "getAvailableDepartmentsResponse", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "output")
    public GetAvailableDepartmentsResponse getAvailableDepartments(
        @WebParam(name = "getAvailableDepartmentsRequest", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "input")
        GetAvailableDepartmentsRequest input);

    /**
     * 
     * @param input
     * @return
     *     returns com.alcatel_lucent.test.soapstub.types.fwmanagement.GetAvailableDialingRulesResponse
     */
    @WebMethod(action = "getAvailableDialingRules")
    @WebResult(name = "getAvailableDialingRulesResponse", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "output")
    public GetAvailableDialingRulesResponse getAvailableDialingRules(
        @WebParam(name = "getAvailableDialingRulesRequest", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "input")
        GetAvailableDialingRulesRequest input);

    /**
     * 
     * @param input
     * @return
     *     returns com.alcatel_lucent.test.soapstub.types.fwmanagement.GetAvailableVoiceMailSystemsResponse
     */
    @WebMethod(action = "getAvailableVoiceMailSystems")
    @WebResult(name = "getAvailableVoiceMailSystemsResponse", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "output")
    public GetAvailableVoiceMailSystemsResponse getAvailableVoiceMailSystems(
        @WebParam(name = "getAvailableVoiceMailSystemsRequest", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "input")
        GetAvailableVoiceMailSystemsRequest input);

    /**
     * 
     * @param input
     * @return
     *     returns com.alcatel_lucent.test.soapstub.types.fwmanagement.GetAvailableDtmfMappingsResponse
     */
    @WebMethod(action = "getAvailableDtmfMappings")
    @WebResult(name = "getAvailableDtmfMappingsResponse", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "output")
    public GetAvailableDtmfMappingsResponse getAvailableDtmfMappings(
        @WebParam(name = "getAvailableDtmfMappingsRequest", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "input")
        GetAvailableDtmfMappingsRequest input);

    /**
     * 
     * @param input
     * @return
     *     returns com.alcatel_lucent.test.soapstub.types.fwmanagement.LoadFrameworkUsersResponse
     */
    @WebMethod(action = "loadFrameworkUsers")
    @WebResult(name = "loadFrameworkUsersResponse", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "output")
    public LoadFrameworkUsersResponse loadFrameworkUsers(
        @WebParam(name = "loadFrameworkUsersRequest", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "input")
        LoadFrameworkUsersRequest input);

    /**
     * 
     * @param input
     * @return
     *     returns com.alcatel_lucent.test.soapstub.types.fwmanagement.GetFrameworkUsersResponse
     */
    @WebMethod(action = "getFrameworkUsers")
    @WebResult(name = "getFrameworkUsersResponse", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "output")
    public GetFrameworkUsersResponse getFrameworkUsers(
        @WebParam(name = "getFrameworkUsersRequest", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "input")
        GetFrameworkUsersRequest input);

    /**
     * 
     * @param input
     * @return
     *     returns com.alcatel_lucent.test.soapstub.types.fwmanagement.GetFrameworkUserResponse
     */
    @WebMethod(action = "getFrameworkUser")
    @WebResult(name = "getFrameworkUserResponse", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "output")
    public GetFrameworkUserResponse getFrameworkUser(
        @WebParam(name = "getFrameworkUserRequest", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "input")
        GetFrameworkUserRequest input);

    /**
     * 
     * @param input
     * @return
     *     returns com.alcatel_lucent.test.soapstub.types.fwmanagement.CreateFrameworkUserResponse
     */
    @WebMethod(action = "createFrameworkUser")
    @WebResult(name = "createFrameworkUserResponse", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "output")
    public CreateFrameworkUserResponse createFrameworkUser(
        @WebParam(name = "createFrameworkUserRequest", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "input")
        CreateFrameworkUserRequest input);

    /**
     * 
     * @param input
     * @return
     *     returns com.alcatel_lucent.test.soapstub.types.fwmanagement.UpdateFrameworkUserResponse
     */
    @WebMethod(action = "updateFrameworkUser")
    @WebResult(name = "updateFrameworkUserResponse", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "output")
    public UpdateFrameworkUserResponse updateFrameworkUser(
        @WebParam(name = "updateFrameworkUserRequest", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "input")
        UpdateFrameworkUserRequest input);

    /**
     * 
     * @param input
     * @return
     *     returns com.alcatel_lucent.test.soapstub.types.fwmanagement.DeleteFrameworkUserResponse
     */
    @WebMethod(action = "deleteFrameworkUser")
    @WebResult(name = "deleteFrameworkUserResponse", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "output")
    public DeleteFrameworkUserResponse deleteFrameworkUser(
        @WebParam(name = "deleteFrameworkUserRequest", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "input")
        DeleteFrameworkUserRequest input);

    /**
     * 
     * @param input
     * @return
     *     returns com.alcatel_lucent.test.soapstub.types.fwmanagement.GetOtsAccountResponse
     */
    @WebMethod(action = "getOtsAccount")
    @WebResult(name = "getOtsAccountResponse", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "output")
    public GetOtsAccountResponse getOtsAccount(
        @WebParam(name = "getOtsAccountRequest", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "input")
        GetOtsAccountRequest input);

    /**
     * 
     * @param input
     * @return
     *     returns com.alcatel_lucent.test.soapstub.types.fwmanagement.UpdateOtsAccountResponse
     */
    @WebMethod(action = "updateOtsAccount")
    @WebResult(name = "updateOtsAccountResponse", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "output")
    public UpdateOtsAccountResponse updateOtsAccount(
        @WebParam(name = "updateOtsAccountRequest", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "input")
        UpdateOtsAccountRequest input);

    /**
     * 
     * @param input
     * @return
     *     returns com.alcatel_lucent.test.soapstub.types.fwmanagement.GetVoiceMailBoxResponse
     */
    @WebMethod(action = "getVoiceMailBox")
    @WebResult(name = "getVoiceMailBoxResponse", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "output")
    public GetVoiceMailBoxResponse getVoiceMailBox(
        @WebParam(name = "getVoiceMailBoxRequest", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "input")
        GetVoiceMailBoxRequest input);

    /**
     * 
     * @param input
     * @return
     *     returns com.alcatel_lucent.test.soapstub.types.fwmanagement.LoadVoiceMailBoxesResponse
     */
    @WebMethod(action = "loadVoiceMailBoxes")
    @WebResult(name = "loadVoiceMailBoxesResponse", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "output")
    public LoadVoiceMailBoxesResponse loadVoiceMailBoxes(
        @WebParam(name = "loadVoiceMailBoxesRequest", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "input")
        LoadVoiceMailBoxesRequest input);

    /**
     * 
     * @param input
     * @return
     *     returns com.alcatel_lucent.test.soapstub.types.fwmanagement.GetVoiceMailBoxesResponse
     */
    @WebMethod(action = "getVoiceMailBoxes")
    @WebResult(name = "getVoiceMailBoxesResponse", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "output")
    public GetVoiceMailBoxesResponse getVoiceMailBoxes(
        @WebParam(name = "getVoiceMailBoxesRequest", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "input")
        GetVoiceMailBoxesRequest input);

    /**
     * 
     * @param input
     * @return
     *     returns com.alcatel_lucent.test.soapstub.types.fwmanagement.CreateVoiceMailBoxResponse
     */
    @WebMethod(action = "createVoiceMailBox")
    @WebResult(name = "createVoiceMailBoxResponse", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "output")
    public CreateVoiceMailBoxResponse createVoiceMailBox(
        @WebParam(name = "createVoiceMailBoxRequest", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "input")
        CreateVoiceMailBoxRequest input);

    /**
     * 
     * @param input
     * @return
     *     returns com.alcatel_lucent.test.soapstub.types.fwmanagement.UpdateVoiceMailBoxResponse
     */
    @WebMethod(action = "updateVoiceMailBox")
    @WebResult(name = "updateVoiceMailBoxResponse", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "output")
    public UpdateVoiceMailBoxResponse updateVoiceMailBox(
        @WebParam(name = "updateVoiceMailBoxRequest", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "input")
        UpdateVoiceMailBoxRequest input);

    /**
     * 
     * @param input
     * @return
     *     returns com.alcatel_lucent.test.soapstub.types.fwmanagement.DeleteVoiceMailBoxResponse
     */
    @WebMethod(action = "deleteVoiceMailBox")
    @WebResult(name = "deleteVoiceMailBoxResponse", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "output")
    public DeleteVoiceMailBoxResponse deleteVoiceMailBox(
        @WebParam(name = "deleteVoiceMailBoxRequest", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "input")
        DeleteVoiceMailBoxRequest input);

    /**
     * 
     * @param input
     * @return
     *     returns com.alcatel_lucent.test.soapstub.types.fwmanagement.GetVoiceMailProfileResponse
     */
    @WebMethod(action = "getVoiceMailProfile")
    @WebResult(name = "getVoiceMailProfileResponse", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "output")
    public GetVoiceMailProfileResponse getVoiceMailProfile(
        @WebParam(name = "getVoiceMailProfileRequest", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "input")
        GetVoiceMailProfileRequest input);

    /**
     * 
     * @param input
     * @return
     *     returns com.alcatel_lucent.test.soapstub.types.fwmanagement.GetAvailableVoiceMailProfilesResponse
     */
    @WebMethod(action = "getAvailableVoiceMailProfiles")
    @WebResult(name = "getAvailableVoiceMailProfilesResponse", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "output")
    public GetAvailableVoiceMailProfilesResponse getAvailableVoiceMailProfiles(
        @WebParam(name = "getAvailableVoiceMailProfilesRequest", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/07/30/ics/fwmanagementSchema", partName = "input")
        GetAvailableVoiceMailProfilesRequest input);

}
