
package com.alcatel_lucent.test.soapstub.notifier;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.alcatel_lucent.test.soapstub.types.notifier.ObjectFactory;
import com.alcatel_lucent.test.soapstub.types.notifier.PingRequest;
import com.alcatel_lucent.test.soapstub.types.notifier.PingResponse;
import com.alcatel_lucent.test.soapstub.types.notifier.SubscribeRequest;
import com.alcatel_lucent.test.soapstub.types.notifier.SubscribeResponse;
import com.alcatel_lucent.test.soapstub.types.notifier.UnsubscribeRequest;
import com.alcatel_lucent.test.soapstub.types.notifier.UnsubscribeResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AlcNotifierPortType", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/05/26/ics/notifierDefinitions")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AlcNotifierPortType {


    /**
     * 
     * @param input
     * @return
     *     returns com.alcatel_lucent.test.soapstub.types.notifier.SubscribeResponse
     */
    @WebMethod(action = "subscribe")
    @WebResult(name = "subscribeResponse", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/05/26/ics/notifierSchema", partName = "output")
    public SubscribeResponse subscribe(
        @WebParam(name = "subscribeRequest", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/05/26/ics/notifierSchema", partName = "input")
        SubscribeRequest input);

    /**
     * 
     * @param input
     * @return
     *     returns com.alcatel_lucent.test.soapstub.types.notifier.UnsubscribeResponse
     */
    @WebMethod(action = "unsubscribe")
    @WebResult(name = "unsubscribeResponse", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/05/26/ics/notifierSchema", partName = "output")
    public UnsubscribeResponse unsubscribe(
        @WebParam(name = "unsubscribeRequest", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/05/26/ics/notifierSchema", partName = "input")
        UnsubscribeRequest input);

    /**
     * 
     * @param input
     * @return
     *     returns com.alcatel_lucent.test.soapstub.types.notifier.PingResponse
     */
    @WebMethod(action = "ping")
    @WebResult(name = "pingResponse", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/05/26/ics/notifierSchema", partName = "output")
    public PingResponse ping(
        @WebParam(name = "pingRequest", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/05/26/ics/notifierSchema", partName = "input")
        PingRequest input);

}
