
package com.alcatel_lucent.test.soapstub.notifier;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * Notifier Web Service.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AlcNotifierService", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/05/26/ics/notifierService", wsdlLocation = "file:/C:/Archivos%20de%20programa/eclipse/workspaceLC/WS_API_Test/bin/AlcNotifier.wsdl")
public class AlcNotifierService
    extends Service
{

    private final static URL ALCNOTIFIERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.alcatel_lucent.test.soapstub.notifier.AlcNotifierService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.alcatel_lucent.test.soapstub.notifier.AlcNotifierService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Archivos%20de%20programa/eclipse/workspaceLC/WS_API_Test/bin/AlcNotifier.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Archivos%20de%20programa/eclipse/workspaceLC/WS_API_Test/bin/AlcNotifier.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ALCNOTIFIERSERVICE_WSDL_LOCATION = url;
    }

    public AlcNotifierService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AlcNotifierService() {
        super(ALCNOTIFIERSERVICE_WSDL_LOCATION, new QName("http://www.alcatel-lucent.com/wsp/ns/2008/05/26/ics/notifierService", "AlcNotifierService"));
    }

    /**
     * 
     * @return
     *     returns AlcNotifierPortType
     */
    @WebEndpoint(name = "AlcNotifierPort")
    public AlcNotifierPortType getAlcNotifierPort() {
        return super.getPort(new QName("http://www.alcatel-lucent.com/wsp/ns/2008/05/26/ics/notifierService", "AlcNotifierPort"), AlcNotifierPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AlcNotifierPortType
     */
    @WebEndpoint(name = "AlcNotifierPort")
    public AlcNotifierPortType getAlcNotifierPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.alcatel-lucent.com/wsp/ns/2008/05/26/ics/notifierService", "AlcNotifierPort"), AlcNotifierPortType.class, features);
    }

}
