
package com.alcatel_lucent.test.soapstub.pbxmanagement;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * PBX management Web Service.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AlcPbxManagementService", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/03/26/ics/pbxmanagementService", wsdlLocation = "file:/C:/Archivos%20de%20programa/eclipse/workspaceLC/WS_API_Test/bin/AlcPbxManagement.wsdl")
public class AlcPbxManagementService
    extends Service
{

    private final static URL ALCPBXMANAGEMENTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.alcatel_lucent.test.soapstub.pbxmanagement.AlcPbxManagementService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.alcatel_lucent.test.soapstub.pbxmanagement.AlcPbxManagementService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Archivos%20de%20programa/eclipse/workspaceLC/WS_API_Test/bin/AlcPbxManagement.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Archivos%20de%20programa/eclipse/workspaceLC/WS_API_Test/bin/AlcPbxManagement.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ALCPBXMANAGEMENTSERVICE_WSDL_LOCATION = url;
    }

    public AlcPbxManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AlcPbxManagementService() {
        super(ALCPBXMANAGEMENTSERVICE_WSDL_LOCATION, new QName("http://www.alcatel-lucent.com/wsp/ns/2008/03/26/ics/pbxmanagementService", "AlcPbxManagementService"));
    }

    /**
     * 
     * @return
     *     returns AlcPbxManagementPortType
     */
    @WebEndpoint(name = "AlcPbxManagementPort")
    public AlcPbxManagementPortType getAlcPbxManagementPort() {
        return super.getPort(new QName("http://www.alcatel-lucent.com/wsp/ns/2008/03/26/ics/pbxmanagementService", "AlcPbxManagementPort"), AlcPbxManagementPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AlcPbxManagementPortType
     */
    @WebEndpoint(name = "AlcPbxManagementPort")
    public AlcPbxManagementPortType getAlcPbxManagementPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.alcatel-lucent.com/wsp/ns/2008/03/26/ics/pbxmanagementService", "AlcPbxManagementPort"), AlcPbxManagementPortType.class, features);
    }

}
