
package com.alcatel_lucent.test.soapstub.apiframework;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.alcatel_lucent.test.soapstub.types.apiframework.ChangePasswordRequest;
import com.alcatel_lucent.test.soapstub.types.apiframework.ChangePasswordResponse;
import com.alcatel_lucent.test.soapstub.types.apiframework.GetFrameworkAccountInfoRequest;
import com.alcatel_lucent.test.soapstub.types.apiframework.GetFrameworkAccountInfoResponse;
import com.alcatel_lucent.test.soapstub.types.apiframework.GetFrameworkAccountRightsRequest;
import com.alcatel_lucent.test.soapstub.types.apiframework.GetFrameworkAccountRightsResponse;
import com.alcatel_lucent.test.soapstub.types.apiframework.LoginRequest;
import com.alcatel_lucent.test.soapstub.types.apiframework.LoginResponse;
import com.alcatel_lucent.test.soapstub.types.apiframework.LoginSupervisorRequest;
import com.alcatel_lucent.test.soapstub.types.apiframework.LoginSupervisorResponse;
import com.alcatel_lucent.test.soapstub.types.apiframework.LogoutRequest;
import com.alcatel_lucent.test.soapstub.types.apiframework.LogoutResponse;
import com.alcatel_lucent.test.soapstub.types.apiframework.ObjectFactory;
import com.alcatel_lucent.test.soapstub.types.apiframework.OpenFrameworkSessionRequest;
import com.alcatel_lucent.test.soapstub.types.apiframework.OpenFrameworkSessionResponse;
import com.alcatel_lucent.test.soapstub.types.apiframework.RestartSessionTimerRequest;
import com.alcatel_lucent.test.soapstub.types.apiframework.RestartSessionTimerResponse;
import com.alcatel_lucent.test.soapstub.types.apiframework.SetSessionTimerValueRequest;
import com.alcatel_lucent.test.soapstub.types.apiframework.SetSessionTimerValueResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AlcApiFrameworkPortType", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/03/26/ics/frameworkDefinitions")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AlcApiFrameworkPortType {


    /**
     * 
     * @param input
     * @return
     *     returns com.alcatel_lucent.test.soapstub.types.apiframework.LoginResponse
     */
    @WebMethod(action = "login")
    @WebResult(name = "loginResponse", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/03/26/ics/frameworkSchema", partName = "output")
    public LoginResponse login(
        @WebParam(name = "loginRequest", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/03/26/ics/frameworkSchema", partName = "input")
        LoginRequest input);

    /**
     * 
     * @param input
     * @return
     *     returns com.alcatel_lucent.test.soapstub.types.apiframework.OpenFrameworkSessionResponse
     */
    @WebMethod(action = "openFrameworkSession")
    @WebResult(name = "openFrameworkSessionResponse", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/03/26/ics/frameworkSchema", partName = "output")
    public OpenFrameworkSessionResponse openFrameworkSession(
        @WebParam(name = "openFrameworkSessionRequest", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/03/26/ics/frameworkSchema", partName = "input")
        OpenFrameworkSessionRequest input);

    /**
     * 
     * @param input
     * @return
     *     returns com.alcatel_lucent.test.soapstub.types.apiframework.LoginSupervisorResponse
     */
    @WebMethod(action = "loginSupervisor")
    @WebResult(name = "loginSupervisorResponse", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/03/26/ics/frameworkSchema", partName = "output")
    public LoginSupervisorResponse loginSupervisor(
        @WebParam(name = "loginSupervisorRequest", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/03/26/ics/frameworkSchema", partName = "input")
        LoginSupervisorRequest input);

    /**
     * 
     * @param input
     * @return
     *     returns com.alcatel_lucent.test.soapstub.types.apiframework.ChangePasswordResponse
     */
    @WebMethod(action = "changePassword")
    @WebResult(name = "changePasswordResponse", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/03/26/ics/frameworkSchema", partName = "output")
    public ChangePasswordResponse changePassword(
        @WebParam(name = "changePasswordRequest", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/03/26/ics/frameworkSchema", partName = "input")
        ChangePasswordRequest input);

    /**
     * 
     * @param input
     * @return
     *     returns com.alcatel_lucent.test.soapstub.types.apiframework.LogoutResponse
     */
    @WebMethod(action = "logout")
    @WebResult(name = "logoutResponse", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/03/26/ics/frameworkSchema", partName = "output")
    public LogoutResponse logout(
        @WebParam(name = "logoutRequest", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/03/26/ics/frameworkSchema", partName = "input")
        LogoutRequest input);

    /**
     * 
     * @param input
     * @return
     *     returns com.alcatel_lucent.test.soapstub.types.apiframework.GetFrameworkAccountInfoResponse
     */
    @WebMethod(action = "getFrameworkAccountInfo")
    @WebResult(name = "getFrameworkAccountInfoResponse", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/03/26/ics/frameworkSchema", partName = "output")
    public GetFrameworkAccountInfoResponse getFrameworkAccountInfo(
        @WebParam(name = "getFrameworkAccountInfoRequest", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/03/26/ics/frameworkSchema", partName = "input")
        GetFrameworkAccountInfoRequest input);

    /**
     * 
     * @param input
     * @return
     *     returns com.alcatel_lucent.test.soapstub.types.apiframework.GetFrameworkAccountRightsResponse
     */
    @WebMethod(action = "getFrameworkAccountRights")
    @WebResult(name = "getFrameworkAccountRightsResponse", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/03/26/ics/frameworkSchema", partName = "output")
    public GetFrameworkAccountRightsResponse getFrameworkAccountRights(
        @WebParam(name = "getFrameworkAccountRightsRequest", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/03/26/ics/frameworkSchema", partName = "input")
        GetFrameworkAccountRightsRequest input);

    /**
     * 
     * @param input
     * @return
     *     returns com.alcatel_lucent.test.soapstub.types.apiframework.SetSessionTimerValueResponse
     */
    @WebMethod(action = "setSessionTimerValue")
    @WebResult(name = "setSessionTimerValueResponse", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/03/26/ics/frameworkSchema", partName = "output")
    public SetSessionTimerValueResponse setSessionTimerValue(
        @WebParam(name = "setSessionTimerValueRequest", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/03/26/ics/frameworkSchema", partName = "input")
        SetSessionTimerValueRequest input);

    /**
     * 
     * @param input
     * @return
     *     returns com.alcatel_lucent.test.soapstub.types.apiframework.RestartSessionTimerResponse
     */
    @WebMethod(action = "restartSessionTimer")
    @WebResult(name = "restartSessionTimerResponse", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/03/26/ics/frameworkSchema", partName = "output")
    public RestartSessionTimerResponse restartSessionTimer(
        @WebParam(name = "restartSessionTimerRequest", targetNamespace = "http://www.alcatel-lucent.com/wsp/ns/2008/03/26/ics/frameworkSchema", partName = "input")
        RestartSessionTimerRequest input);

}
